version: 2.1

orbs:
  cypress: cypress-io/cypress@3.1.3
  slack: usertech/circleci-slack-orb@5.1.0

jobs:
  cypress_run:
    executor: cypress/default
    steps:
      - checkout
      - cypress/install
      - run:
          name: Run Cypress Tests
          command: |
            npx cypress run --spec cypress/e2e/helpdesk/screenshots.cy.js
      - slack/notify:
          channel: alerts
          event: fail
          template: default_fail_1

  test2:
    executor: cypress/default
    steps:
      - checkout
      - cypress/install
      - run:
          name: Run Cypress Tests for test2
          command: |
            npx cypress run --spec cypress/e2e/testing/test.cy.js
      - slack/notify:
          channel: alerts
          event: fail
          template: default_fail_1

  schedule:
    executor: cypress/default
    steps:
      - checkout
      - cypress/install
      - run:
          name: Run Cypress Tests on Schedule
          command: |
            npx cypress run --spec cypress/e2e/helpdesk/screenshots.cy.js
      - slack/notify:
          channel: alerts
          event: fail
          template: default_fail_1

workflows:
  version: 2
  test_and_notify:
    jobs:
      - cypress_run:
          context: slack
      - test2:
          context: slack
      - schedule:
          context: slack

shedules:
  manual_trigger:
    cron: "0 0 * * *"