version: 2.1
orbs:
  cypress: cypress-io/cypress@3.1.3
workflows:
  version: 2
  test:
    jobs:
      - cypress/run:
          install-browsers: true
          start-command: 'npm run start'
          cypress-command: 'npx cypress run --spec cypress/e2e/helpdesk/screenshots.cy.js'
          post-steps:
            - run: ls
            - store_artifacts:
                path: cypress/screenshots
workflows:
  version: 2
  schedule:
    jobs:
      - cypress/run:
          install-browsers: true
          start-command: 'npm run start'
          cypress-command: 'npx cypress run --spec cypress/e2e/helpdesk/screenshots.cy.js'
          post-steps:
            - run: ls
            - store_artifacts:
                path: cypress/screenshots
    triggers:
      - schedule:
          cron: "25 16 * * *"
          filters:
            branches:
              only:
                - main
