version: 2.1

orbs:
  cypress: cypress-io/cypress@3.1.3


jobs:
  test_firefox:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Cypress Tests
          command: npx cypress run --browser firefox --spec "cypress/e2e/helpdesk/screenshots.cy.js,cypress/e2e/testing/test.cy.js"
      - store_artifacts:
          path: cypress/screenshots
      - store_artifacts:
          path: cypress/videos

workflows:
  version: 2
  test:
    jobs:
      - test_firefox


  schedule:
    jobs:
      - test_firefox
    triggers:
      - schedule:
          cron: "00 18 * * *"
          filters:
            branches:
              only:
                - main


