version: 2.1

orbs:
  cypress: cypress-io/cypress@3.1.3
  slack: usertech/circleci-slack-orb@5.1.0
workflows:
  version: 2
  test:
    jobs:
      - cypress/run:
          start-command: 'npm run start'
          cypress-command: npx cypress run --spec cypress/e2e/helpdesk/screenshots.cy.js
          post-steps:
            - run: ls
            - store_artifacts:
                path: cypress/screenshots
                
  test2:
    jobs:
      - slack/context: # Agregamos el contexto de Slack al trabajo test2
          context: slack
      - cypress/run:
          cypress-command: npx cypress run --spec cypress/e2e/testing/test.cy.js
          post-steps:
            - run: ls
            - store_artifacts:
                path: cypress/videos
            - slack/notify: # Aquí agregamos la notificación de Slack
                channel: alerts
                event: fail
                template: default_fail_1
            

  schedule:
    jobs:
      - cypress/run:
          start-command: 'npm run start'
          cypress-command: npx cypress run --spec cypress/e2e/helpdesk/screenshots.cy.js
          post-steps:
            - run: ls
            - store_artifacts:
                path: cypress/screenshots
    triggers:
      - schedule:
          cron: "00 18 * * *"
          filters:
            branches:
              only:
                - main
